### PR TITLE
validate object-keys are sorted

### PR DESCRIPTION
**Pull request by kaizhu256**
this patch will warn if object-keys are not sorted, e.g.

```js
let aa = {
    "bb": 1,
    "aa": 1,
    "cc": 1
};
/*
warning
Unsorted object-keys.
    "aa": 1
*/
```

demo of patch available @ https://kaizhu256.github.io/JSLint/branch.sort_object_keys/index.html

image

### CODE REVIEW

**Comment by douglascrockford** [comment]
There are cases where other orderings are preferred, such as putting an 'id' or 'type' field first.

**Comment by douglascrockford** [comment]
Ok, go ahead.

**Comment by kaizhu256** [comment]
k will reopen and cleanup the patch a little

**Comment by kaizhu256** [comment]
expanded scope to include destructured parameters as well:

```javascript
let {bb, aa} = {};
function foo({dd, cc, ee}) {
    return {cc, ee, dd};
}

/*
Parameter 'aa' not listed in alphabetical order. // line 1
Parameter 'cc' not listed in alphabetical order. // line 2
Property name 'dd' not listed in alphabetical order. // line 3
*/
```

**Comment by kaizhu256** [comment]
fixed with commit b135742d7db698df3b05581a7819bd9869540b5c

**Comment by pschmidtboeing** [comment]
How do I avoid encountering this error if I use Object.keys with an array-like object for a series of regex match/replace, where a regex match on a subsequent property name in the array-like object is dependent on the string change that occurred due to the previous item in the array-like object? Example:
function b_cleanString(str) {
    var map = {
      "ZZZ ": " ",
      " *: *": ":"
    };
    var prop = "";
    var regex = "";
    var i = 0;
    for (prop = Object.keys(map); i < prop.length; i += 1) {
      regex = new RegExp(prop[i], "gi");
      str = str.replace(regex, map[prop[i]]);
    }
    return str;
  }
b_cleanString("testing ZZZ :ZZZ 123");
The order in the above "map" array-like object causes the function to return "testing:123", but it would return "testing ZZZ: 123" if "map" was sorted to prevent the warning enabled by this patch.

**Comment by kaizhu256** [comment]
new version v2021.5.27 has been pushed to branch `master` and https://www.jslint.com/jslint.js with new directive `/*jslint unordered*/`.

also in future, please use https://github.com/jslint-org/jslint/issues to raise issues/feature-requests/ideas ; )

image

**Pull request closed without merging**
