### PR TITLE
v2021.5.26

### PR DESCRIPTION
**Pull request by kaizhu256**
- coverage - increase regression testing and coverage to 98.41% (almost 100% baby!)
- ci - fix ci silently failing in node-v12 and node-v14.
- cli - add env var JSLINT_CLI to force-trigger cli in jslint.js (used for code-coverage of cli).
- jslint - add "globalThis" to default globals.
- jslint - add new rules unordered_param_a, unordered_property_a, that warn if parameters and properties are listed in nonascii-order.
- jslint - fix bug where (global) functionage missing properties finally and try.
- jslint - fix bug failing to parse unicode "\\u{12345}".
- jslint - fix bug falsely warning against conditional-chaining-operator "?.".
- jslint - remove deadcode for preaction-binary-".".
- jslint - remove deadcode warning bad_option_a.
- website - add fork-me ribbon.
- website - load index.html with example code.
- website - merge file report.js into browser.js.

demo of release-candidate available @ https://www.jslint.com/branch.beta/index.html

image

### CODE REVIEW

**Comment by chrswk** [comment]
Not sure if this is the right place, but I feel like the `unordered_param_a/unordered_property_a` is quite the change and to just have it on by default, without an option to disable it. I've been using JSLint for years and have always gone with what ever changes were introduced, because in the end they made my code better. But this feels a bit weird?

**Comment by kaizhu256** [comment]
hi @chrswk,  jslint will be shipping with [ignore-macros](https://github.com/jslint-org/jslint/pull/281) shortly.  i eventually want to get rid of most of the directives, and use `/*jslint ignore:...*/`  macros whenever a need to ignore warnings arise, e.g.:

```javascript
/* jslint ignore:start */
/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.org/license */
!function(e,t){"use strict";"object"==typeof module&&...
/* jslint ignore:end */

let err = {
    statusCode: 404,
    // suppress warning unordered_property_a
    message: "Not Found", // jslint ignore:line
    type: "httpError",
    url: "https://www.undefined.com/undefined"
};
```

would that satisfy your needs?  and appreciate knowing the cli helps : )

**Comment by chrswk** [comment]
Thank for the input.

To be honest, I'm not really a fan of the macros instead of the config flags, but I see why it would be easier in some cases. If that is the "solution", I think I will go through the trouble of reordering all my properties and parameters, even if that's a lot of work.

But out of curiosity: What is the reason or expected benefit of having ordered properties/parameters?

**Comment by kaizhu256** [comment]
when inspecting/editing large dictionaries/json-objects with > 50 items, scrolling around the editor to find a key becomes troublesome if they're not sorted in some canonical order.

you've made me consider maybe adding a new directive `classical` or something similar which allows jslint to only enforce warnings pre v2021.5.26.

in meantime, since jslint is tool-less, you are free to disable (or add) warnings by simply editing `jslint.js`:

```diff
https://raw.githubusercontent.com/jslint-org/jslint/v2021.5.26/jslint.js
diff --git a/.a00.js b/.a00.js
index 2b62242..bee1d2a 100644
--- a/.a00.js
+++ b/.a00.js
@@ -2769,9 +2769,9 @@ function parameter_list() {
                     survey(subparam);
                     a = b;
                     b = String(subparam.value || subparam.id);
-                    if (a > b) {
-                        warn("unordered_param_a", subparam);
-                    }
+                    //!! if (a > b) {
+                        //!! warn("unordered_param_a", subparam);
+                    //!! }
                     advance();
                     signature.push(subparam.id);
                     if (next_token.id === ":") {
@@ -3123,9 +3123,9 @@ prefix("{", function () {
             advance();
             a = b;
             b = String(name.value || name.id);
-            if (a > b) {
-                warn("unordered_property_a", name);
-            }
+            //!! if (a > b) {
+                //!! warn("unordered_property_a", name);
+            //!! }
             if (
                 (name.id === "get" || name.id === "set")
                 && next_token.identifier
@@ -3284,9 +3284,9 @@ function do_var() {
                 survey(name);
                 a = b;
                 b = String(name.value || name.id);
-                if (a > b) {
-                    warn("unordered_param_a", name);
-                }
+                //!! if (a > b) {
+                    //!! warn("unordered_param_a", name);
+                //!! }
                 advance();
                 if (next_token.id === ":") {
                     advance(":");
```

**Comment by kaizhu256** [comment]
new version v2021.5.27 has been pushed to branch `master` and https://www.jslint.com/jslint.js with new directive `/*jslint unordered*/`.

also in future, please use https://github.com/jslint-org/jslint/issues to raise issues/feature-requests/ideas ; )

image

**Comment by chrswk** [comment]
Oh no. As a developer who fights every day to not have to add new config parameters for X and Y to my software, I now have a config parameter on my conscience! 😅

I really appreciate your efforts. Your explanation makes sense and I think it should also reduce the mental effort of reasoning about a "logical" order. If you will excuse me, I have some properties and params reordering to do...

**Pull request merged**
