### PR TITLE
Added links to homepage

### PR DESCRIPTION
**Pull request by UnrealApex**
Added links in pages that redirect the user back to the main page

### CODE REVIEW

**Comment by kaizhu256** [comment]
thx for the pr, but unfortunately have to reject because the link you added won't be clickable.  as you can see in screenshot below, the entire title is masked behind the `fork on github` banner element.

image

**Comment by UnrealApex** [comment]
The link is in the `help.html` which doesn't have the banner element.

**Comment by kaizhu256** [comment]
ah ok.  can you also do it for `function.html` as well?

**Comment by UnrealApex** [comment]
Sure.

**Comment by kaizhu256** [comment]
thx

**Pull request merged**
